### ISSUE TITLE
Movement?

### ISSUE THREAD

**Issue by GetContented** [mwotton/datomic-peer#1]
Hi, I wonder if you've done any more work on this, or know of the existence of another project that might do this?

**Comment by mwotton** [comment]
nope. :) sorry, i was just playing around, I have no intention to keep working on this.

**Comment by GetContented** [comment]
Ah ok thanks :) Can I ask why?

**Comment by mwotton** [comment]
just not using datomic, and have plenty of other things on my to-do list :/ Sorry I couldn't be more helpful - @bitemyapp is the only person I can think of who knows both datomic and Haskell, but I suspect he would tell you to run.

**Comment by GetContented** [comment]
That makes perfect sense :) Was just curious, is all.

Haha yeah, he rather hates Datomic, I noticed. :) Not entirely sure why. I'm building trees, and in this case the standard relational table structure isn't really what I'm after. Also, I kind of fell in love with the idea that the db client is part of your codebase - it makes huge sense to me rather than use stored procedures or something ugly like that.

Thanks!

**Comment by bitemyapp** [comment]
@JulianLeviston love doesn't make for a working database.

**Comment by GetContented** [comment]
@bitemyapp indeed!

**Comment by GetContented** [comment]
@bitemyapp by the way, if you feel like saying more, please do. If not, well that's fine, too :)
